const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = 'ONLINE_USERS';
const ONLINE_USER_SET = 'ONLINE_USER_SET';
const ONLINE_USER_DELETE = 'ONLINE_USER_DELETE';

const GROUP_USER_TYPING = 'GROUP_USER_TYPING';
const GROUP_USER_STOPPED_TYPING = 'GROUP_USER_STOPPED_TYPING';

const REFETCH_PROFILE = 'REFETCH_PROFILE';
const REFETCH_GROUP_CHAT_LIST = 'REFETCH_GROUP_CHAT_LIST'
const REFETCH_GROUP_CHAT_MEMBERS = 'REFETCH_GROUP_CHAT_MEMBERS';

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  ONLINE_USER_SET,
  ONLINE_USER_DELETE,
  GROUP_USER_TYPING,
  GROUP_USER_STOPPED_TYPING,
  REFETCH_PROFILE,
  REFETCH_GROUP_CHAT_LIST,
  REFETCH_GROUP_CHAT_MEMBERS,
};
